#!/usr/bin/bash
############################################################################### 
#                                   bashrc
############################################################################### 
# This is the user specific startup configuration for non-login shells

# Set the XDG_CONFIG_DIR if it is not set

if [[ -v XDG_CONFIG_DIR ]]; then
    export XDG_CONFIG_DIR=~/.config
fi

# Configuration environment:
#######################################
export ALACRITTYRC=$XDG_CONFIG_DIR/alacritty/alacritty.yml

export BASHRC=$XDG_CONFIG_DIR/bash/bashrc
export BASH_PROFILE=$XDG_CONFIG_DIR/bash/bash_profile
export BASH_ALIAS=$XDG_CONFIG_DIR"/bash/alias"
export BASH_HELPER=$XDG_CONFIG_DIR/bash/helper

# readline configuration file
export INPUTRC=$XDG_CONFIG_DIR/readline/inputrc

export LIQUIDPROMPTRC=$XDG_CONFIG_DIR/liquidprompt/liquidpromptrc

export SCREENRC=$XDG_CONFIG_DIR/screen/screenrc

export SWAYRC=$XDG_CONFIG_DIR/sway/config

export I3RC=$XDG_CONFIG_DIR/i3/config

export TRIDACTYLRC=$XDG_CONFIG_DIR/tridactyl/tridactylrc

export XINITRC=$XDG_CONFIG_DIR/xorg/xinitrc
export XMODMAP=$XDG_CONFIG_DIR/xorg/xmodmap
export XRESOURCES=$XDG_CONFIG_DIR/xorg/nord.xresources

export VIMRC=$XDG_CONFIG_DIR/vim/vimrc
export VIM_FILETYPES=$XDG_CONFIG_DIR/vim/filetype.vim
export VIM_PLUGINS=$XDG_CONFIG_DIR/vim/plugins.vim
export VIM_HELPER=$XDG_CONFIG_DIR/vim/helper.vim
export VIM_YCM=$XDG_CONFIG_DIR/vim/global_extra_conf.py


# General
############################################################################### 
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# # Some handy aliases
if [[ -f ${BASH_ALIAS} ]]; then
    source $BASH_ALIAS
else 
    echo '$BASH_ALIAS not found, skipping...'
fi

# Source some general helper functions
if [[ -f $BASH_HELPER ]]; then
    source $BASH_HELPER
else
    echo '$BASH_HELPER not found, skipping...'
fi

if [[ -f $LIQUIDPROMPTRC ]]; then 
    source $LIQUIDPROMPTRC
fi

if [[ -f /usr/bin/virtualenvwrapper.sh ]]; then
    source /usr/bin/virtualenvwrapper.sh
fi


# Settings
############################################################################### 

# Applications
#######################################
# Vim is the default editor
export VISUAL=vim

# Change location of .bash_history to not clutter $HOME
HISTFILE=~/.cache/bash/history

# Do not store duplicates in history
HISTCONTROL=ignoredups

# fix non-KDE desktop
QT_QPA_PLATFORMTHEME=qt5ct

# Directories for python environments
WORKON_HOME=~/.cache/virtualenvs

# Unlimited lines in history
HISTSIZE=1000000000

# Filesize limit of the history file
HISTFILESIZE=10000 

shopt -s histappend

# Add some items to PATH
#######################################
pathadd /usr/local/bin
pathadd ~/.local/bin
pathadd ~/.local/share
pathadd ~/.local/share/python/scripts
pathadd ~/.local/lib/python3.9/site-packages

## liquidprompt prefix to show running process in GNU screen window name
# LP_PS1_PREFIX="\[\\033k\\033\\\\\]"

## Python specific
################################################################################ 
## Path for custom python modules (somehow not working on startup)
pythonpathadd /usr/lib/python3.9/site-packages/
pythonpathadd ~/.local/share/lib/python3.9/site-packages/
